name: CD

on:
  push:
    branches:
      - 'prod'
      - 'dev'
  pull_request:
    branches:
      - 'prod'
      - 'dev'

jobs:
  Deployment_to_AWS:
    environment: 
        name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    permissions: 
        contents: read
        packages: write
        actions: write
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install
          cd iac
          npm install

      - name: Deploy to AWS
        run: |
          cd iac
          cdk synth
          cdk deploy --require-approval never
        env:
            STAGE: ${{ github.event_name }}
            AZURE_URL: ${{ secrets.AZURE_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
