name: CI / CD

stages:
  - build
  - test
  - deploy

build:
  stage: build
  jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '20.x'

        - name: Install dependencies
          run: |
            npm install
            cd iac
            npm install

test:
  stage: test
  jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
        - name: Run tests
          run: npm test
          env:
            AZURE_URL: ${{ secrets.AZURE_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}

        - name: Stop action
          if: ${{ failure() }}
          run: exit 1

# deploy:
#   stage: deploy
#   jobs:
#     deploy_job:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Configure AWS credentials
#           uses: aws-actions/configure-aws-credentials@v1
#           with:
#             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#             aws-region: ${{ secrets.AWS_REGION }}

#         - name: Deploy to AWS
#           run: |
#             echo "Deploying to AWS"
#             cd iac
#             cdk deploy --require-approval never
#           env:
#             STAGE: ${{ github.ref_name }}
#             AZURE_URL: ${{ secrets.AZURE_URL }}
#             SECRET_KEY: ${{ secrets.SECRET_KEY }}
#             AWS_REGION: ${{ secrets.AWS_REGION }}
#             AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
